'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Assignment10

    Partial Public Class Employees
        Public Property Emp_Id As String
        Public Property First_Name As String
        Public Property Last_Name As String
        Public Property Dept_Id As Nullable(Of Integer)
    
    End Class

End Namespace
